---
- name: 'Origin Certs | Change admin group if on MacOS'
  set_fact:
    admin_group: admin
  when: ansible_os_family == "Darwin"

- name: 'Origin Certs | Create certs directory'
  file:
    path: /certs
    state: directory
    mode: 0755
    group: '{{ origin_certs_group }}'

- name: 'Origin Certs | Install certs for each domain'
  include_tasks: install.yml
  with_items: '{{ origin_certs }}'
  loop_control:
    loop_var: cert
    label: '{{ cert.domain }}'
